[aws.session]
region="us-east-1"

[aws.dynamodb]
create_table=true
table_name="braid_triggers_triggers"
BillingMode="PAY_PER_REQUEST"


[aws.dynamodb.client_params]
endpoint_url="http://localhost:4566"


[log]
debug = true
